//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleLaughsNurseryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealChart
    {
        public string Days { get; set; }
        public string Breakfast { get; set; }
        public string Lunch { get; set; }
        public string Snacks { get; set; }
        public int MealID { get; set; }
    }
}
