//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleLaughsNurseryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public string Timings { get; set; }
        public Nullable<int> Rate_Monthly { get; set; }
        public Nullable<int> Rate_weekly { get; set; }
        public Nullable<int> Rate_3DaysPerWeek { get; set; }
        public int Rate_ID { get; set; }
    }
}
